### ISSUE TITLE
Fix folders of midis at a time?

### ISSUE THREAD

**Issue by DigitallyRemastered** [tg44/MidiSplitter#1]
Hi!
Your program works wonders! I tried it on a midi I found and it worked immediately! How might we get this to do the same thing to multiple midis ~ perhaps all the midi files in a folder?

Perhaps a for loop?

**Comment by tg44** [comment]
In long run I want to do it a graphical interface for faster and more logical use, and more costumizable logic.

You can load and run in all the midis if u r using linux-cli, or cygwin or powershell. How to start links:
http://stackoverflow.com/questions/6329505/how-to-rename-all-file-in-a-folder-with-a-suffix-in-a-single-unix-command
http://tweaks.com/windows/49459/batch-file-rename-with-windows-powershell/
(not rename them instead run the jar)

**Comment by DigitallyRemastered** [comment]
I'm a bit confused. From the link, I'm thinking that if I rename a file Titanic_[original name].midi, it would process all the midis into Titanic_out_[original name].midi

However, you said in parentheses that it's not to rename the midis, but instead run the jar. I'm not quite sure what you meant there. Your help is extremely appreciated!

**Comment by DigitallyRemastered** [comment]
I got it to work by incorporating a for loop. I'm not great with coding, and what you've done goes way over my head, but:

One could set a for loop around the main code using the control variable as an index in the args
array. You would increment n by two every go around so that you could use the odd integers of n to signify input midis and even integers of n for output midis. Then one only needs to edit the names of the corresponding argument names in the properties to be the names of the midis that need to be modified. 

Yay beginner programming basics :3

**Comment by tg44** [comment]
I commited a new version, its not tested, but I think its working :) It can do the dir convert with pre or postfixing the files. If u tricky with the prefixes I think u coud take the output to folders too.

**Comment by DigitallyRemastered** [comment]
I'm confused about the difference between a prefixed and postfixed file, and so I don't know what the indices 2 and 3 are or what their purpose is :[

**Comment by tg44** [comment]
Prefix "asd_": file.mid->asd_file.mid
Postfix "_asd": file.mid->file_asd.mid

The correct parameterise like: d:\midi -po _out

The prefix was bugged a bit, I resolved it now.

**Comment by DigitallyRemastered** [comment]
-So is the rationale that files in a folder with a prefix or postfix will be fixed while those without them will be left unprocessed? 
-How do you tell the program which directory to look in? Project properties?

**Comment by tg44** [comment]
I made a graphical interface, the preworked functionality is comed back, and working.

**Comment by tg44** [comment]
Resolved! Working functionality.
