### ISSUE TITLE
Preserve Tempo data

### ISSUE THREAD

**Issue by DigitallyRemastered** [tg44/MidiSplitter#5]
Hey again tg44. Here's another thing to work on when you have time ;)
The tempo of all the midi's input to the program gets reset to a constant default tempo of 120BPM. I'm sure this problem is similar enough to the pitch bend problem that once you figure out one, the other should be easy.

**Comment by tg44** [comment]
It will be fast fix, I will do it today or Saturday.

**Comment by tg44** [comment]
Try now, I think its working.

**Comment by DigitallyRemastered** [comment]
Yup, that did the trick.
